### ISSUE TITLE
gemini error

### ISSUE THREAD

**Issue by afifaljafari112** [VishwaGauravIn/twitter-auto-poster-bot-ai#2]
GoogleGenerativeAIError: [429 Too Many Requests] Quota exceeded for quota metric 'Generate Content API requests per minute' and limit 'GenerateContent request limit per minute for a region' of service 'generativelanguage.googleapis.com' for consumer 'project_number:121598310693'. [{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"RATE_LIMIT_EXCEEDED","domain":"googleapis.com","metadata":{"quota_limit":"GenerateContentRequestsPerMinutePerProjectPerRegion","quota_limit_value":"0","quota_location":"us-east2","service":"generativelanguage.googleapis.com","consumer":"projects/121598310693","quota_metric":"generativelanguage.googleapis.com/generate_content_requests"}},{"@type":"type.googleapis.com/google.rpc.Help","links":[{"description":"Request a higher quota limit.","url":"https://cloud.google.com/docs/quotas/help/request_increase"}]}]
    at makeRequest (/home/runner/work/twittard/twittard/node_modules/@google/generative-ai/dist/index.js:257:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async generateContent (/home/runner/work/twittard/twittard/node_modules/@google/generative-ai/dist/index.js:6[14](https://github.com/afifaljafari112/twittard/actions/runs/10960826228/job/30436342757#step:5:15):22)
    at async run (/home/runner/work/twittard/twittard/index.js:30:18)

**Comment by VishwaGauravIn** [comment]
This is because you have exceed the rate limits of your Gemini API on a minute basis. Try sending only 2 tweets in a minute and not more than that.

**Comment by afifaljafari112** [comment]
how to edit cron or github runner? by default config you have, its limit by 1 tweet in 1 hour right?

**Comment by VishwaGauravIn** [comment]
you can edit this file `twitter-auto-poster-bot-ai/edit/main/.github/workflows/twitter.yml`

yes it runs every hour now but you can change it by changing the:

```
on:
  schedule:
    - cron: "0 * * * *"
```

cron parameter, you can generate cron code from here: https://www.freeformatter.com/cron-expression-generator-quartz.html
